print('MENGHITUNG RUMUS-RUMUS FISIKA')
import math
print('1.MENGHITUNG PERCEPATAN BENDA')
v0=(int(input('masukkan nilai kecepatan awal benda')))
vt=(int(input('masukkan nilai kecepatan akhir benda')))
t0=(int(input('masukkan nilai waktu awal benda')))
tt=(int(input('masukkan nilai waktu akhir benda')))
a=(vt-v0)/(tt-t0)
print('Jadi nilai percepatan yang diperoleh yaitu',a,'m/s^2')
print("")
print('2.MENGHITUNG HUKUM NEWTON 2')
m=(int(input('masukkan nilai massa benda')))
g=(float(input('masukkan nilai gravitasi bumi')))
F=m*g
print('Jadi gaya yang diperlukan yaitu',F,'N')
print("")
print('3.MENGHITUNG TEOREMA PHYTAGORAS')
a=(int(input('masukkan panjang sisi yang pertama')))
b=(int(input('masukkan panjang sisi yang kedua')))
c=math.sqrt(a*2+b*2)
print('Jadi nilai dari sisi miring segitiga yaitu',c,)
